spring.datasource.url=jdbc:postgresql://db:5432/mundo_viagens
spring.datasource.username=${DB_USER:mundo}
spring.datasource.password=${DB_PASSWORD:mundo_dev}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=false